language: python
env:
  - TOX_ENV=py26-trunkdeps
  - TOX_ENV=py27-trunkdeps
  - TOX_ENV=pypy-trunkdeps
install:
  - pip install -e .
  - pip install tox
  - pip install coveralls
script:
  - tox -e $TOX_ENV
after_success:
  - coveralls
